FROM node:20-alpine AS builder
WORKDIR /app
COPY ./frontend .
RUN npm install && npm run build

FROM caddy:2-alpine
COPY --from=builder /app/dist /usr/share/caddy
COPY caddy/Caddyfile.prod /etc/caddy/Caddyfile
