FROM golang:1.24.1-alpine AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/main cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/cmd/main .
EXPOSE 8080
CMD ["./main"]  