name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env file for backend
        run: echo "${{ secrets.ENV_BACKEND }}" > ./backend/.env

      - name: Check .env
        run: cat ./backend/.env

      - name: Create .env file for frontend
        run: echo "${{ secrets.ENV_FRONTEND }}" > ./frontend/.env

      - name: Check .env
        run: cat ./frontend/.env

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use

      - name: Build and push `backend` Docker image
        run: |
          docker buildx build \
            --tag ghcr.io/nicrozj/task-backend:latest \
            --push \
            --file backend/Dockerfile.prod \
            ./backend

      - name: Build and push `proxy` Docker image
        run: |
          docker buildx build \
            --tag ghcr.io/nicrozj/task-proxy:latest \
            --push \
            --file frontend/Dockerfile.prod \
            .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HOST_KEY }}

      - name: Copy .env file to server
        run: |
          echo "${{ secrets.ENV_DB }}" > db.env
          scp -o StrictHostKeyChecking=no db.env ${{ secrets.HOST_USER }}@${{ secrets.HOST_ADDR }}:task-manager/db.env

      - name: Copy docker-compose.yml to server
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.prod.yml ${{ secrets.HOST_USER }}@${{ secrets.HOST_ADDR }}:task-manager

      - name: Pull and Start Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_USER }}@${{ secrets.HOST_ADDR }} 'cd task-manager && docker compose -f docker-compose.prod.yml pull && docker compose -f docker-compose.prod.yml up -d'
